### ISSUE TITLE
tox.ini is missing

### ISSUE THREAD

**Issue by hackebrot** [vintasoftware/cookiecutter-tapioca#7]
The Makefile provides a `test-all` target that runs tox, however the generated api wrapper does not have `tox.ini` file. :smile:

**Comment by filipeximenes** [comment]
You are right. 
Right now I haven't came to a decision on if wrappers should be tested and if so, how should this be done, how much tapioca should get involved, and how to build a useful testing tool. (this is for the tapioca-wrapper project, just opened an issue: https://github.com/vintasoftware/tapioca-wrapper/issues/93)

For cookiecutter-tapioca right now the correct action is to clean the Makefile and leave only what is useful.
