### ISSUE TITLE
The link to tapioca-wrapper documentation on README.md leads to non existent page

### ISSUE THREAD

**Issue by vu3jej** [vintasoftware/cookiecutter-tapioca#8]
The link to tapioca-wrapper documentation on README.md points to http://tapioca-wrapper.readthedocs.org/en/latest/quickstart/ instead of http://tapioca-wrapper.readthedocs.org/en/stable/. I can submit a pull request if the second link is appropriate.

**Comment by filipeximenes** [comment]
Forgot to update this after changing the docs from MD to RST. The correct link is: 
http://tapioca-wrapper.readthedocs.org/en/stable/quickstart.html

Can you make the PR? Thanks!

**Comment by filipeximenes** [comment]
Also, I should review tapioca clients... some of them might have broken links as well

**Comment by vu3jej** [comment]
Sorry! I was swamped with work for the last two days! Will make the PR tonight!
